# Generated by Django 6.1.1 on 2026-09-26 14:11

import carts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('expires_at', models.DateTimeField(default=carts.models.get_default_cart_expiration, verbose_name='زمان انقضا')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_gold_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت روز طلا (هر گرم) زمان ثبت')),
                ('wage_percent', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد اجرت ساخت')),
                ('profit_percent', models.FloatField(default=7.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد سود طلافروش')),
                ('tax_percent', models.FloatField(default=9.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد مالیات')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
