# Generated by Django 6.1.1 on 2026-09-30 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_store'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='wage_percent',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='constant_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ ثابت (سکه)'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='wage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اجرت (تومان)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='daily_gold_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت روز طلا 18 عیار (زمان ثبت)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='profit_percent',
            field=models.FloatField(default=7.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد سود'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tax_percent',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد مالیات'),
        ),
    ]
