# Generated by Django 6.1.1 on 2026-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bale_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='آیدی بله'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='آیدی تلگرام'),
        ),
    ]
