# Generated by Django 6.1.1 on 2026-09-28 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_token', models.CharField(max_length=100, unique=True, verbose_name='توکن ربات تلگرام')),
                ('bot_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='یوزرنیم ربات')),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی کانال')),
                ('admin_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='چت آیدی ادمین برای پشتیبانی')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zarinpal_merchant_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='مرچنت آیدی زرین\u200cپال')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فروشگاه')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت در ربات')),
                ('total_spent', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع خرید از این فروشگاه')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='بلاک شده توسط این فروشگاه')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_profiles', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'unique_together': {('store', 'user')},
            },
        ),
    ]
