# Generated by Django 6.1.1 on 2026-10-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='platform',
            field=models.CharField(choices=[('telegram', 'تلگرام'), ('bale', 'بله')], default='telegram', max_length=20, verbose_name='پلتفرم'),
        ),
    ]
