# Generated by Django 6.1.1 on 2026-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='bot_token',
        ),
        migrations.AddField(
            model_name='store',
            name='bale_bot_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='توکن بله'),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='توکن تلگرام'),
        ),
    ]
