# Generated by Django 6.1.1 on 2026-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_bot_token_store_bale_bot_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='admin_chat_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bot_username',
        ),
        migrations.RemoveField(
            model_name='store',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='store',
            name='admin_chat_id_bale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='چت آیدی ادمین برای پشتیبانی بله'),
        ),
        migrations.AddField(
            model_name='store',
            name='admin_chat_id_telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='چت آیدی ادمین برای پشتیبانی تلگرام'),
        ),
        migrations.AddField(
            model_name='store',
            name='bale_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='یوزرنیم ربات بله'),
        ),
        migrations.AddField(
            model_name='store',
            name='channel_id_bale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی کانال بله'),
        ),
        migrations.AddField(
            model_name='store',
            name='channel_id_telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' آیدی کانال تلگرام'),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='یوزرنیم ربات تلگرام'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bale_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات بله'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن ربات تلگرام'),
        ),
    ]
