# Generated by Django 6.1.1 on 2026-09-28 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل فاکتور (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=15, verbose_name='وضعیت تراکنش')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ارجاع زرین\u200cپال')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری (RefID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت نهایی پرداخت شده')),
                ('gold_weight', models.FloatField(verbose_name='وزن طلای خریداری شده (گرم)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
