# Generated by Django 6.1.1 on 2026-09-30 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_store'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='constant_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مقدار ثابت (سکه پارسیان)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ornamental', 'طلای زینتی'), ('parsian', 'سکه پارسیان')], default='ornamental', max_length=20, verbose_name='نوع محاسبه'),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_percent',
            field=models.FloatField(default=7.0, help_text='حداکثر ۷ درصد', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='درصد سود'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percent',
            field=models.FloatField(default=10.0, help_text='حداکثر ۱۰ درصد', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='درصد مالیات'),
        ),
        migrations.AddField(
            model_name='product',
            name='wage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اجرت (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='فروشگاه'),
        ),
    ]
