# Generated by Django 6.1.1 on 2026-09-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_constant_fee_product_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت پایانی طلا ۱۸ عیار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
