# Generated by Django 6.1.1 on 2026-09-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_dailygoldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoldprice',
            name='coin_gram_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سکه گرمی'),
        ),
        migrations.AddField(
            model_name='dailygoldprice',
            name='coin_half_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='نیم سکه'),
        ),
        migrations.AddField(
            model_name='dailygoldprice',
            name='coin_new_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سکه امامی'),
        ),
        migrations.AddField(
            model_name='dailygoldprice',
            name='coin_old_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سکه طرح قدیم'),
        ),
        migrations.AddField(
            model_name='dailygoldprice',
            name='coin_quarter_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='ربع سکه'),
        ),
    ]
