# Generated by Django 6.1.1 on 2026-10-02 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_dailygoldprice_coin_gram_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wage',
        ),
        migrations.AddField(
            model_name='product',
            name='wage_percent',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='درصد اجرت'),
        ),
    ]
